name: Release

on:
  push:
    tags: ["v*.*.*"]

jobs:
  build:
    permissions:
      id-token: write
      attestations: write
    uses: ./.github/workflows/build.yml

  github:
    name: GitHub Releases
    needs: build

    runs-on: macos-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifacts
        id: download
        uses: actions/download-artifact@v5
        with:
          path: /tmp/artifacts

      - name: Prepare assets
        env:
          ARTIFACTS: ${{ steps.download.outputs.download-path }}
        id: prepare
        run: |
          asset_path="/tmp/assets"
          mkdir -p "$asset_path"
          for artifact in "$ARTIFACTS"/*/; do
            basename "$artifact" | \
              xargs -I {} zip -jr "$asset_path"/{}.zip "$artifact"
          done

      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
          TAG: ${{ github.ref_name }}
        run: |
          gh release create --draft --verify-tag "$TAG" /tmp/assets/*.zip
